Feature - Interaction context subscriptions
robinpowered/react-native-interaction-provider pull request #1
Opened 2017-06-20 19:23 UTC by ajwhite

This hits the [next stage of the roadmap](https://github.com/robinpowered/react-native-interaction-provider#roadmap) by adding subscriptions to interactivity changes.

Example:

Say we have a screen that should autodismiss after 1m of inactivity:
```js
class SomeSreen extends React.Component {
  static contextTypes = {
    interactionProvider: React.PropTypes.object.isRequired
  };

  componentDidMount() {
    this.subscription = this.context.interactionProvider.subscribeForInactivity(
      60 * 1000, 
      this.onInactive.bind(this)
    )
  }

  componentWillUnmount() {
    this.subscription.remove()
  }

  onInactive() {
    this.props.navigator.pop()
  }

  ...
}
```

This also decouples the `InteractionProvider` from the `InteractionContainer`. We may not always want both of them together, so you can now use either one. The `InteractionContainer` was for scenarios like such:

```js
<InteractionContainer timeout={60 * 1000} onInactive={() => ...}>
   <ComponentToObserveInteractionsOn />
</InteractionContainer>
```

This also introduces a convenient `withInteractionProps` component factory function, allowing components to receive `active` and `inactive` props:

```js
function InteractiveView ({inactive}) {
  const style = {backgroundColor: inactive ? 'gray' : 'red'}
  return (
    <View style={style} />
  )
}

const InteractionAwareView = withInteractionProps(InteractiveView, {duration: 60 * 1000})
```

2017-06-28 15:34 UTC, christophermark requested changes
In addition to the code changes, can you update the readme with the behavior changes?

2017-06-28 15:34 UTC, christophermark commented on index.js
> +import withInteractionProps from './withInteractionProps';
These can be shortened as:
```js
export {default as InteractionContainer} from './interactionContainer';
```

2017-06-28 15:34 UTC, christophermark commented on interactionProvider.js
> +   * @param {number} duration The amount of time, in miliseconds, for a period of time to
Might be clearer as:
> The amount of time, in miliseconds, after which the interaction is considered inactive.

This comment also applies to duplicate docblocks in this PR.

2017-06-28 15:34 UTC, christophermark commented on withInteractionProps.js
> +      inactive: false
Are these mutually exclusive?

At first glance this seems like something that could be combined into a single prop: `active`, which is true when active and false when inactive.

2017-06-28 16:36 UTC, ajwhite commented on index.js
> +import withInteractionProps from './withInteractionProps';
I wanted to provide both default and named exports -- but I suppose I could just do the default one twice:

```js
export {default} from './interactionContainer'
export {default as InteractionContainer} from './interactionContainer'
...
```
Or maybe even the following might work, will have to test:
```js
export {default, default as InteractionProvider} from './interactionProvider'
```

2017-06-28 16:38 UTC, ajwhite commented on withInteractionProps.js
> +      inactive: false
Yep! But i wanted to be as ergonomic as possible to satisfy the use case where you might only care about one of these. Certainly `active` implies `inactive`, and visa-versa, but wanted to make both available for it to be as easy to use as possible

For example, in a case where we only care about `active`, we can inspect `this.props.active`. And alternatively if we only care about `inactive`, we can inspect `this.props.inactive`.

2017-06-28 18:06 UTC, christophermark commented on index.js
> +import withInteractionProps from './withInteractionProps';
Mind replying to the thread with what did/didn't work? Really curious

2017-06-28 18:07 UTC, christophermark commented on withInteractionProps.js
> +      inactive: false
I guess it doesn't hurt to add it, but `!active` seems pretty straightforward to me if you're detecting inactivity.

2017-07-05 16:02 UTC, ajwhite commented
Nice, the following export **did work**

```js
export {default, default as InteractionProvider} from './interactionProvider'
```

Feedback is in

2017-07-06 14:28 UTC, christophermark approved these changes
👍  Great work here

2017-07-06 14:28 UTC, merged